name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest Docker image tag
        id: get_tag
        run: |
          LATEST_TAG=$(docker run --rm ghcr.io/${{ github.repository }}-api:main --version 2>&1 || true)
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_tag.outputs.latest_tag }}
          name: Release v${{ steps.get_tag.outputs.latest_tag }}
          body: |
            ## Docker Image
            The latest Docker image is available at:
            ```
            ghcr.io/${{ github.repository }}-api:latest
            ```
            
            ### Pull the Image
            ```bash
            docker pull ghcr.io/${{ github.repository }}-api:latest
            ```
            
            ### Run the Container
            ```bash
            docker run -d \
              -p 7090:8080 \
              -e ASPNETCORE_ENVIRONMENT=Production \
              ghcr.io/${{ github.repository }}-api:latest
            ```
            
            See the [README.md](https://github.com/${{ github.repository }}/blob/main/README.md) for more details.
          draft: false
          prerelease: false
          generate_release_notes: true 